import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const workflowPath = fileURLToPath(
  new URL("../.github/workflows/preview-smoke.yml", import.meta.url),
);
const workflow = readFileSync(workflowPath, "utf8");

function blockBetween(startMarker, endMarker) {
  const start = workflow.indexOf(startMarker);
  const end = workflow.indexOf(endMarker, start + startMarker.length);
  if (start < 0 || end < 0) {
    throw new Error(`workflow block not found: ${startMarker}`);
  }
  return workflow.slice(start, end);
}

const doOnlyConfig = blockBetween(
  "      - name: Prepare isolated preview config",
  "      - name: Apply preview D1 migrations",
);

const denoConfig = blockBetween(
  "      - name: Prepare isolated Deno preview config",
  "      - name: Check Preview Deno health",
);

blockBetween(
  "      - name: Validate Preview Deno configuration",
  "      - name: Prepare isolated Deno preview config",
);

test("DO-only Preview config removes all Deno and prepare bindings", () => {
  for (const name of [
    "DENO_TOKENIZER_ENDPOINT",
    "DENO_TOKENIZER_THRESHOLD_BYTES",
    "DENO_TOKENIZER_TIMEOUT_MS",
    "DENO_TOKENIZER_AUTH_TOKEN",
    "DENO_PREPARE_ENDPOINT",
    "DENO_PREPARE_THRESHOLD_BYTES",
  ]) {
    assert.match(
      doOnlyConfig,
      new RegExp(`delete config\\.vars\\.${name};`),
      `Preview config must delete ${name}`,
    );
  }
});

test("DO-only Preview config maps the isolated input limit", () => {
  assert.ok(
    doOnlyConfig.includes("config.vars.MAX_INPUT_BYTES = process.env.PREVIEW_MAX_INPUT_BYTES"),
    "Preview config must set MAX_INPUT_BYTES from PREVIEW_MAX_INPUT_BYTES",
  );
  assert.equal(doOnlyConfig.includes("process.env.MAX_INPUT_BYTES"), false);
});

test("Deno Preview config is generated by the prepare-aware mapper", () => {
  assert.ok(
    denoConfig.includes("node scripts/preview-worker-config.mjs"),
    "Deno Preview config must use the prepare-aware mapper",
  );
  assert.ok(
    denoConfig.includes("MAX_INPUT_BYTES=${maxInputBytes}"),
    "Deno Preview config must assert the mapped input limit",
  );
  assert.ok(
    denoConfig.includes("OCTG_EXPECTED_MAX_INPUT_BYTES=${maxInputBytes}"),
    "Deno Preview config must assert the expected input limit",
  );
});

test("Deno Preview config unsets an absent prepare pair before mapping", () => {
  assert.ok(
    denoConfig.includes("unset PREVIEW_DENO_PREPARE_ENDPOINT PREVIEW_DENO_PREPARE_THRESHOLD_BYTES"),
    "Deno Preview config must unset absent prepare variables",
  );
});

test("Preview workflow never references production Deno endpoint variables", () => {
  const lines = workflow.split("\n").map((line) => line.trim());
  const hasProductionTokenizerEndpoint = lines.some((line) =>
    line.startsWith("DENO_TOKENIZER_ENDPOINT:")
  );
  const hasProductionPrepareEndpoint = lines.some((line) =>
    line.startsWith("DENO_PREPARE_ENDPOINT:")
  );
  assert.equal(hasProductionTokenizerEndpoint, false);
  assert.equal(hasProductionPrepareEndpoint, false);
  assert.equal(workflow.includes("PRODUCTION_DENO_TOKENIZER_ENDPOINT"), false);
  assert.equal(workflow.includes("PRODUCTION_DENO_TOKENIZER_AUTH_TOKEN"), false);
});

test("Preview Worker secrets never include the production Deno auth token", () => {
  const invalidUpload = blockBetween(
    "      - name: Upload invalid-auth Worker version",
    "      - name: Route invalid-auth version at 0% traffic",
  );
  const validUpload = blockBetween(
    "      - name: Upload valid-auth Worker version",
    "      - name: Route valid-auth version at 0% traffic",
  );

  assert.ok(invalidUpload.includes("preview-invalid-token-sentinel"));
  assert.equal(
    invalidUpload.includes("PRODUCTION_DENO_TOKENIZER_AUTH_TOKEN"),
    false,
  );
  assert.ok(validUpload.includes("DENO_PREVIEW_TOKENIZER_AUTH_TOKEN"));
  assert.equal(
    validUpload.includes("PRODUCTION_DENO_TOKENIZER_AUTH_TOKEN"),
    false,
  );
});
